version: '3'
services:
  db:
    image: postgres:11
    restart: 'always'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clean-architecture-02
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: 'no'
    ports:
      - 5051:8080
